# Generated by Django 2.0 on 2017-12-11 08:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171210_1520'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
