# Generated by Django 2.0 on 2018-02-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180206_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitems',
            name='reps_type',
            field=models.CharField(choices=[(('a', 'Επαναλήψεις'), ('b', 'Χρόνος'))], default='a', max_length=1),
        ),
    ]
