# Generated by Django 2.0 on 2018-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectitems_reps_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('first_page', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(default='Trainer', max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, default='Add descriprion here', max_length=250, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectitems',
            name='reps_type',
            field=models.CharField(choices=[('a', 'Επαναλήψεις'), ('b', 'Χρόνος')], default='a', max_length=1),
        ),
    ]
