# Generated by Django 2.0 on 2018-02-07 05:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180206_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
