# Generated by Django 2.0 on 2018-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180208_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rounds',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
