# Generated by Django 2.0 on 2018-02-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180208_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rounds',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
