# Generated by Django 2.0 on 2018-02-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180208_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitems',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
