# Generated by Django 2.0 on 2017-12-11 08:22

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=gallery.models.upload_location, validators=[gallery.models.validate_size]),
        ),
    ]
