# Generated by Django 2.0 on 2017-12-31 14:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_image, validators=[blog.models.validate_size]),
        ),
    ]
